sudo: required

language: python

python:
  - "2.7"
  - "3.6"

env:
  - ADMIN_PARTY=true COUCHDB_VERSION=apache/couchdb:2.1.1
  - ADMIN_PARTY=false COUCHDB_VERSION=apache/couchdb:2.1.1
  - ADMIN_PARTY=true COUCHDB_VERSION=apache/couchdb:1.6.1
  - ADMIN_PARTY=false COUCHDB_VERSION=apache/couchdb:1.6.1

services:
  - docker

before_install:
  - docker pull $COUCHDB_VERSION
  - docker run -d -p 5984:5984 $COUCHDB_VERSION

install: "pip install -r requirements.txt && pip install -r test-requirements.txt"

before_script:
    # Make sure CouchDB is up
    - while [ $? -ne 0 ]; do sleep 1 && curl -v http://localhost:5984; done
    - curl -X PUT http://localhost:5984/_users
    - curl -X PUT http://localhost:5984/_replicator

# command to run tests
script:
    - pylint ./src/cloudant
    - nosetests -w ./tests/unit

notifications:
  email: false
