sudo: required

language: python

python:
  - "2.7"
  - "3.5"

env:
  - ADMIN_PARTY=true
  - ADMIN_PARTY=false

services:
  - docker

before_install:
  - docker pull apache/couchdb:2.1.1
  - docker run -d -it -p 5984:5984 apache/couchdb:2.1.1 --with-admin-party-please --with-haproxy

install: "pip install -r requirements.txt && pip install -r test-requirements.txt"

before_script:
    # Make sure CouchDB is up
    - while [ $? -ne 0 ]; do sleep 1 && curl -v http://localhost:5984; done
    - curl -X PUT http://localhost:5984/_users
    - curl -X PUT http://localhost:5984/_replicator

# command to run tests
script:
    - pylint ./src/cloudant
    - nosetests -w ./tests/unit

notifications:
  email: false
